In [2]:
import numpy as np
import random
from time import sleep
import math
from Game import *
from learning import *

In [3]:
iterations1=100
iterations2=1000
iterations3=2000
learning_randomly_4x4x4(iterations1,iterations2,iterations3)

Utility function learning randomly with 100 iterations:
[[[ -2   5  -5   8]
  [ 11   3   2  -2]
  [  7   4  -2 -12]
  [  1   5  11  12]]

 [[ 12  -1  -6 -12]
  [ -1  -1  14 -12]
  [-12   5   7  -2]
  [ -2 -16  16   8]]

 [[ -6 -13  -3  -7]
  [ -6  -3  13   5]
  [  0 -16  -8   0]
  [  5  -1  -8   2]]

 [[  1   2  -4  -4]
  [  2  -7   2   7]
  [ -7  -1   8   2]
  [  6 -19   2  13]]]
Utility function learning randomly with 1000 iterations:
[[[ 47 -36  24  11]
  [-18 -18 -28  -1]
  [-26 -39   7 -35]
  [ 35   3 -42  44]]

 [[  9   9 -15 -43]
  [-18  50  61 -22]
  [ -8  54  41   0]
  [ 28 -48  13  10]]

 [[ -2 -35   5  -2]
  [-14 -12  25   3]
  [-18  -1  48 -38]
  [ 19   0 -73 -34]]

 [[ 53   0 -34   6]
  [ 13  -2  28 -15]
  [  3  -9  13 -33]
  [ 29 -10 -17  55]]]
Utility fuction learning randomly with 2000 iterations:
[[[106 -27  20  61]
  [ -9 -39 -64 -18]
  [-16 -94  -8 -53]
  [ 70  -8 -18  19]]

 [[ -9  27 -64 -58]
  [-59  45  74 -21]
  [-13 125  53 -34]
  [-14 -71  20 -17]]

 [[ 21 -34 

In [5]:
iterations1=100
iterations2=1000
iterations3=2000
learning_with_exploration(iterations1,iterations2,iterations3)

Utility function learning randomly with 100 iterations:
[[[ -2  -4   6  -9]
  [ -8  -4  -4   1]
  [  2  -2   7   9]
  [  0   2  -4   5]]

 [[  3  -6   1  -1]
  [-10  -2  -4   3]
  [ -6  -5  -8  -6]
  [  3  -2   1 -11]]

 [[ -1  -9  -3  18]
  [-11   4   2 -10]
  [ -7   6   7   1]
  [ -5  -7 -12  14]]

 [[ -8   0  -1  20]
  [ -1  -8  18  16]
  [ 17   1  11   3]
  [ 17   9 -11  39]]]
Utility function learning randomly with 1000 iterations:
[[[ -32  -27   -5  -10]
  [ -34  -16  -63   -1]
  [   3  -70  -45   24]
  [  -8  -57  -35   20]]

 [[ -22    2   17  -48]
  [ -65  -22   13  -33]
  [   3  -26   27  -37]
  [   0  -14   -6  -50]]

 [[  35  -64   -8   60]
  [-137  102   14   -3]
  [ -59   72   -3   -1]
  [  17  -19  -57  -11]]

 [[  97   57  117  249]
  [-159   91  141   53]
  [  24   68  136  -33]
  [ 127   45 -159  403]]]
Utility fuction learning randomly with 2000 iterations:
[[[ -73  -21  -27  -48]
  [ -64  -56 -123  -23]
  [ -34  -88  -62    4]
  [  25  -66  -72   56]]

 [[ -90  -26 