In [1]:
import numpy as np
import random
from time import sleep
import math
from Game import *
from learning import *

In [4]:
iterations1=100
iterations2=1000
iterations3=2000
learning_randomly_4x4x4(iterations1,iterations2,iterations3)

Utility function learning randomly with 100 iterations:
[[[ -9   1   0  -6]
  [  9  -1  -1 -12]
  [ -5  -5  -3  -3]
  [  3  -1   8  -3]]

 [[  1   0  14  -3]
  [ 10  16  -1  -1]
  [ -7  10  -6   3]
  [ 15  13  -4  -7]]

 [[  2  -3  -1  -2]
  [ -6   2  -1   0]
  [ 11  14  -2  12]
  [  5   3   1  -6]]

 [[  6   1  -2   2]
  [ -2 -12  -5 -12]
  [-10  -9  -9  -7]
  [  3  -3  -9  14]]]
Utility function learning randomly with 1000 iterations:
[[[-15  -2  25 -42]
  [-22  -1 -25  -6]
  [-23  38  -4   1]
  [ 29 -37 -52  24]]

 [[-33   0 -29   2]
  [ 17  71  59 -13]
  [-12 -13  47 -58]
  [-10  23 -18  41]]

 [[-42  -4 -44  21]
  [-14  93  12  27]
  [ -6  56  15  -8]
  [  6 -21   0  -5]]

 [[ 19 -41 -11  68]
  [-28 -79 -26 -21]
  [  2 -30 -48  38]
  [ 24  23  12  50]]]
Utility fuction learning randomly with 2000 iterations:
[[[ 41 -19  36  13]
  [-44   0 -86 -14]
  [-27  47   8 -50]
  [  2 -10 -90  89]]

 [[-47 -20 -49  -6]
  [-23  86 101 -15]
  [-12   3  97 -95]
  [-67  32 -40  63]]

 [[-30  -7 