In [7]:
import numpy as np
import random
from time import sleep
import math
from Game import *
from learning import *

In [8]:
iterations1=100
iterations2=1000
iterations3=2000
learning_randomly_4x4x4(iterations1,iterations2,iterations3)

Utility function learning randomly with 100 iterations:
[[[ 14  -3   4 -13]
  [ 13   2   9  -6]
  [-11 -16  -6  -5]
  [  3  -6   5  -7]]

 [[  3  -4   6 -15]
  [  3  15  16  -6]
  [  5 -10  10  -6]
  [  0   7 -13   5]]

 [[ -2  10   2   7]
  [-11  12   2  17]
  [  7   0  -1   0]
  [-17 -10   4   6]]

 [[ -1  -5  -3  11]
  [ -9  -4  10 -17]
  [  1  -3  -6  -1]
  [ 19  -7   3  -7]]]
Utility function learning randomly with 1000 iterations:
[[[ 55 -36  -9   3]
  [  2  15 -30 -20]
  [-34 -11 -49  -2]
  [ 32  -9 -39  14]]

 [[-31  -2  28 -20]
  [ 44  65  43 -29]
  [ 26  33  43 -22]
  [  3  30 -63 -15]]

 [[ -8   5 -33 -15]
  [-38  67  35  45]
  [-10   1  67  12]
  [-46 -14 -18 -23]]

 [[ 18 -36  30  62]
  [-32   7 -28 -21]
  [-17  -8 -37   2]
  [ 25 -42  -1  36]]]
Utility fuction learning randomly with 2000 iterations:
[[[117 -36 -39  65]
  [-28 -18  -8 -33]
  [-72 -31 -95 -29]
  [ 57   6 -63  34]]

 [[-57 -37  54  -6]
  [ 83 100  76 -23]
  [ 34  56  56  -7]
  [ -7  18 -39  -2]]

 [[-12 -11 

In [9]:
iterations1=100
iterations2=1000
iterations3=2000
learning_with_exploration_and_exploitation(iterations1,iterations2,iterations3)

NameError: name 'learning_with_exploration_and_exploitation' is not defined