In [9]:
import numpy as np
import random
from time import sleep
import math
from Game import *
from learning import *

In [10]:
iterations1=100
iterations2=1000
iterations3=2000
learning_randomly_4x4x4(iterations1,iterations2,iterations3)

Utility function learning randomly with 100 iterations:
[[[-10   6   5   0]
  [  5  -2  -1  -9]
  [ -1   0 -14  -7]
  [ 23   6  -9  -6]]

 [[  6   9  -2  -6]
  [ -1   4  11 -13]
  [  9   4   7   1]
  [ 14   1  -7  -2]]

 [[ -3  -3  -9 -10]
  [ -4  14  23   3]
  [  3   5   9   4]
  [ -2 -19   3  16]]

 [[ -8  -1  -1  -5]
  [-18  -1  -3  -5]
  [  2  -3  10 -17]
  [  7  -7  -7   6]]]
Utility function learning randomly with 1000 iterations:
[[[ 37  26  20  20]
  [  1  -7  15 -33]
  [ -6 -41  -7  -7]
  [ 49   1 -26 -12]]

 [[ 19 -31 -25 -11]
  [-17  13  30  -1]
  [  1  47  36  -5]
  [  4  11 -35 -10]]

 [[-48 -26  10  15]
  [  6  37  36  -9]
  [ 10  31  24  -4]
  [-22 -56   0   5]]

 [[ 42 -22  11  32]
  [-43  21 -51 -38]
  [-18   4  -9 -33]
  [ 12  18 -46  55]]]
Utility fuction learning randomly with 2000 iterations:
[[[  48   49  -12   62]
  [  -1  -51  -25  -69]
  [ -31  -50  -14  -44]
  [  87   18  -15    9]]

 [[ -10  -22  -27   -1]
  [ -33   22   65  -41]
  [   8   89   45  -16]
  [  

In [11]:
iterations1=1
iterations2=10
iterations3=20000
learning_with_exploration_and_exploitation(iterations1,iterations2,iterations3)

Utility function learning randomly with 1 iterations:
[[[-3  0  0  0]
  [ 0  0  1  0]
  [ 0  0  0  0]
  [ 0  0 -2  0]]

 [[ 0  0 -2  2]
  [-2  2  2  2]
  [-2  3 -2  2]
  [ 2  2 -2 -2]]

 [[ 2  2 -2  2]
  [-2 -3  2 -3]
  [ 2  2 -2 -1]
  [-2 -3  2  2]]

 [[-1  3 -3  3]
  [-3  3 -3  1]
  [-1  3  3 -3]
  [ 3 -3  1 -1]]]
Utility function learning randomly with 10 iterations:
[[[-4 -2  0 -2]
  [-1 -1  3  2]
  [ 2  1 -3  0]
  [ 0  1 -1  3]]

 [[-1  1 -2  4]
  [-1  1  1  3]
  [-1  2 -3  2]
  [ 3  1  0 -4]]

 [[ 2  3  4 -3]
  [ 0 -7  0 -4]
  [ 4 -4 -4  0]
  [-1  0  1  3]]

 [[-1  6 -6  0]
  [ 4  4  2 -4]
  [ 6  4 -2 -4]
  [ 2 -2 -8  6]]]
Utility fuction learning randomly with 20000 iterations:
[[[ -390  -448  -629  -308]
  [ -487  -660  -709  -487]
  [ -248  -685  -513  -452]
  [  -35  -494  -265   154]]

 [[ -515  -547  -717  -714]
  [ -659  -147  -138  -520]
  [ -575    99    10  -649]
  [ -740  -452  -477  -626]]

 [[  795  -430    -8  1247]
  [-1002   873   763   -79]
  [ -928  1130   616  