In [1]:
import numpy as np
import random
from time import sleep

In [2]:
#Dont touch this functions!!Copy here when it is checked and is ok
#Converting a number into some base N with vector length L
#Number that players have: player1=1 or player2=2
#We will consider during the whole exercise matrix as i, rows as j and columns as k
# x is column, y is row for a 2D matrix
player1=1
player2=2
#Create a new board
def create_board():
    mat=np.array([[[0 for i in range(4)] for j in range(4)] for k in range(4)])
    return mat
#Checking empty spaces
def possibilities(board):
    pos=[]
    N=len(board)
    for i in range(N):
        for j in range(N):
            for k in range(N):
                if board[i,j,k]==0:
                   pos.append((i,j,k))               
    return(pos)
#Assignating a random position to me or the adversary considering the possibilities
def random_place(board,player,possible):
    #possible=possibilities(board)
    selection=random.choice(possible)
    possible.remove[selection]# remove the possibility
    board[selection]=player
    return board
#Different manners of win in the game
#Row checker. For now only for each matrix separated
def row2D_winner(board,player):
    N=len(board)
    for i in range(N):
        for j in range(N):
            win=True
            for k in range(N):
                if board[i,j,k]!=player:
                    win=False
                    break
            if win==True:
                return win
    return win  
def column2D_winner(board,player):
    N=len(board)
    #Matrix i
    for i in range(N):
        #Column k
        for k in range(N):
            win=True
            #Row j
            for j in range(N):
                if board[i,j,k]!=player:
                    win=False
                    break
            if win==True:
                return win
    return win  
def column3D_winner(board,player):
    N=len(board)
    #Row j
    for j in range(N):
        #Column k
        for k in range(N):
            win=True
            #matrix i
            for i in range(N):
                if board[i,j,k]!=player:
                    win=False
                    break
            if win==True:
                    return win            
    return win  
#Try of both diagonals (2D)
def diags2D_winner(board,player):
    N=len(board)
    #Matrix i
    for i in range(N):
        win=True
        #Diags
        for j in range(N):
            if board[i,j,j]!=player:
                win=False
                break
        if win==True:
            return win 
     #Matrix i   
    for i in range(N):
        win=True
        #Rows and columns
        for j in range(N):
            if board[i,j,(N-1)-j]!=player:
                win=False
                continue
        if win==True:
            return win
    return win 
#See if there is a winner in 3D direction x
def winner3Dx(board,player):
    #Rows j
    N=len(board)
    for j in range(N):
        #Level j
        win=True
        #Level i
        for i in range(N):
            if board[i,j,i]!=player:
                win=False
                continue
        if win==True:
            return win
    #Rows j for the other diagonal
    for j in range(N): 
        win=True
        #Level i
        for i in range(N):
            if board[i,j,N-1-i]!=player:
                win=False
                continue
        if win==True:
            return win
    return win    
def winner3Dy(board,player):
    #Columns k
    N=len(board)
    for k in range(N):
        win=True
        #Level i
        for i in range(N):
            if board[i,i,k]!=player:
                win=False
                continue
        if win==True:
            return win
    #Now to the other diagonal
    #Row k
    for k in range(N):
        win=True
        #Level i
        for i in range(N):
            if board[i,N-1-i,k]!=player:
                win=False
                continue
        if win==True:
            return win
    return win    
def winner3Ddiag(board,player):
    #Level i
    win=True
    for i in range(N):
        if board[i,i,i]!=player:
            win=False
            continue
    if win==True:
        return win
    #Now to other diagonal
    win=True
    for i in range(N):
        if board[i,N-1-i,N-1-i]!=player:
            win=False
            continue
    if win==True:
        return win
    #Third 3D diagonal
    win=True
    for i in range(N):
        if board[i,i,N-1-i]!=player:
            win=False
            continue
    if win==True:
        return win
    #Last diagonal
    win=True
    for i in range(N):
        if board[i,N-1-i,i]!=player:
            win=False
            continue
    if win==True:
        return win
    return win
#See if there is a winner
def winner(board,player):
    winner=row_winner(board,player) or column_winner(board,player)\
    or diags_winner(board,player) or column3D_winner(board,player)\
    or winner3Dx(board,player) or winner3Dy(board,player)\
    or winner3Ddiag(board,player)
    return winner

In [3]:
#Function to evaluate if there is a winner, or if there is not a winner but there is a draw
#Or if there is not winner or tie
def evaluate(board):
    winner=0
    for player in [1,2]:
        if winner(board,player):
            winner=player
    if np.all(board!=0) and winner==0:
        winner=-1
    return winner

In [4]:
def play_game():
    board,winner,counter=create_board(),0,1
    print(board)
    while winner==0:
        for player in [1,2]:
            board=random_place(board,player)
            print("Board after " + str(counter) + " move") 
            print(board) 
            counter=counter+1
            winner=evaluate(board)
            if winner!=0:
                break
    return winner    # my information    

In [5]:
play_game()

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Board after 1 move
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 1 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


TypeError: 'int' object is not callable

In [8]:
def play(numberOfTial):
    utilityArray = create_board()
    for n in range(numOfTrial):
        
    

In [9]:

print(utilityArray)

NameError: name 'utilityArray' is not defined